version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'tqrd'
    working_dir: '/root'
    tty: true
    volumes:
      - ./src:/root/src
      - ./resources:/root/resources
